export const CREATE_SUBJECT = `CREATE_SUBJECT`;
export const LOAD_SUBJECTS_SUCCESS = `LOAD_SUBJECT_SUCCESS`;
export const CREATE_SUBJECT_SUCCESS = `CREATE_SUBJECT_SUCCESS`;
export const UPDATE_SUBJECT_SUCCESS = `UPDATE_COURSE_SUCCESS`;
export const BEGIN_API_CALL = `BEGIN_API_CALL`;
export const API_CALL_ERROR = `API_CALL_ERROR`;
